spring.application.name=KetchupBackend
spring.data.mongodb.uri=mongodb://localhost:27017/test
#habilita los logs de debug para ver en tiempo real la manipulación de las variables
logging.level.ketchupapp.ketchupbackend=DEBUG
#habilita los logs de la base de datos, sirve para ver que la base de datos este respondiendo a las llamadas.
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
